abshaadi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from app.views import home, dashboard, profiles_filters, site_management
from app.views.staff import package_management, user_management
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test

def staff_member_required(view_func=None, login_url='/page_403/'):
    """
    Decorator for views that checks that the user is logged in and is a staff
    member, redirecting to the login page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_active and u.is_staff,
        login_url=login_url
    )
    if view_func:
        return actual_decorator(view_func)
    return actual_decorator



# Authorization
urlpatterns = [
    path('',home.HomeView.as_view(), name="home"),
    path('page_403/',home.page_403, name="page_403" ),
    path('login/', home.LoginView.as_view(template_name = 'app/base/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/base/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('registration/', home.register_form, name='registration'),
    path('my_redirect_page/', home.my_redirect_page, name='my_redirect_page'),
    path('change_password/', home.change_password, name='change_password'),
]

# Site Managers
urlpatterns += [
    path('staff/religion-management/', never_cache(staff_member_required(site_management.ReligionManagementView.as_view())), name='religion_management'),
    path('load_religions_into_db/', never_cache(staff_member_required(site_management.load_religions_into_db)), name="load_religions_into_db"),
    path('add_religion/', never_cache(staff_member_required(site_management.add_religion)), name="add_religion"),
    path('staff/delete_religion/<int:ins>/', never_cache(staff_member_required(site_management.delete_religion)), name="delete_religion"),
    path('add_caste/', never_cache(staff_member_required(site_management.add_caste)), name="add_caste"),
    path('staff/delete_caste/<int:ins>/', never_cache(staff_member_required(site_management.delete_caste)), name="delete_caste"),
    path('staff/site_managers/load_countries/', never_cache(staff_member_required(site_management.add_countries_to_db)), name="add_countries_to_db"),
]

# Common Urls
urlpatterns += [
    path('get_states_dropdown/', never_cache(login_required(site_management.get_states_dropdown)), name="get_states_dropdown"),
    path('get_cities_dropdown/', never_cache(login_required(site_management.get_cities_dropdown)), name="get_cities_dropdown"),
    path('get_castes_dropdown/', never_cache(login_required(site_management.get_castes_dropdown)), name="get_castes_dropdown"),
]

# Dashboard
urlpatterns += [
    path('staff/dashboard/', never_cache(staff_member_required(dashboard.StaffDashboardView.as_view())), name="staff_dashboard"),
    path('dashboard/', never_cache(login_required(dashboard.UserDashboardView.as_view())), name="dashboard"),
]


# Profile
urlpatterns += [
    path('profile/', never_cache(login_required(profiles_filters.UserProfileView.as_view())), name="user_profile"),
    path('edit_personal_info/', never_cache(login_required(profiles_filters.edit_personal_info)), name="edit_personal_info"),
    path('upload_profile_pic/', never_cache(login_required(profiles_filters.upload_profile_pic)), name="upload_profile_pic"),
    path('edit_other_detalis/', never_cache(login_required(profiles_filters.edit_other_detalis)), name="edit_other_detalis"),
    path('edit_summary_detalis/', never_cache(login_required(profiles_filters.edit_summary_detalis)), name="edit_summary_detalis"),
    path('edit_family_detalis/', never_cache(login_required(profiles_filters.edit_family_detalis)), name="edit_family_detalis"),
]


# Staff
urlpatterns += [
    path('staff/package_management/view/', never_cache(staff_member_required(package_management.PackageManagementView.as_view())), name="staff_package_management_view"),
    path('staff/user_management/users/view/', never_cache(staff_member_required(user_management.UserManagementView.as_view())), name="user_management_view"),
    path('staff/user_management/users/delete/<int:ins>/', never_cache(staff_member_required(user_management.delete_user)), name="delete_user"),
    path('staff/user_management/staff/view/', never_cache(staff_member_required(user_management.StaffManagementView.as_view())), name="staff_management_view"),
    path('staff/user_management/staff/add/', never_cache(staff_member_required(user_management.add_staff)), name="add_staff"),
]


# Search Pages
urlpatterns += [
    path('search_results/', never_cache(login_required(profiles_filters.MySearchView.as_view())), name="user_search_results"),
    path('save_partner_preferences/', never_cache(login_required(profiles_filters.save_partner_preferences)), name="save_partner_preferences")
]

# Partner Profile Views
urlpatterns += [
    path('connect_msg_save/', never_cache(login_required(profiles_filters.connect_message)), name="connect_msg_save"),
    path('profile_like/<int:to_user_id>/', never_cache(login_required(profiles_filters.profile_like)), name="profile_like"),
    path('partner_profile/<int:user_id>/', never_cache(login_required(profiles_filters.partner_profile_view)), name="partner_profile"),
]


# EMAILS
urlpatterns += [
    path('confirmemail/<qstr>', home.confirmemail, name="confirmemail"),
    path('confirmemail/<qstr>/', home.confirmemail, name="confirmemail"),
]

#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from django.conf import settings

import uuid
import os


#***********************************************************************
#
#***********************************************************************

class Religion(models.Model):
    religion_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
        unique = True,
    )

    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.religion_name.capitalize()

    class Meta:
        verbose_name_plural = "Religions"


#***********************************************************************
#
#***********************************************************************

class Caste(models.Model):
    religion = models.ForeignKey(
        Religion,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    caste_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.caste_name.capitalize()

    class Meta:
        verbose_name_plural = "Religious Castes"

#***********************************************************************
#
#***********************************************************************

class Countries(models.Model):
    country_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.country_name.capitalize()

    class Meta:
        verbose_name_plural = "Countries List"

#***********************************************************************
#
#***********************************************************************

class Countries_States(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    state_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.state_name.capitalize()

    class Meta:
        verbose_name_plural = "States List"

#***********************************************************************
#
#***********************************************************************

class Countries_Cities(models.Model):
    country = models.ForeignKey(
        Countries,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    state_name = models.ForeignKey(
        Countries_States,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    city_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    is_active = models.BooleanField(
        default = True,
        db_index = True,
    )

    def __str__(self):
        return self.city_name.capitalize()

    class Meta:
        verbose_name_plural = "Cities List"


#***********************************************************************
#
#***********************************************************************

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


#***********************************************************************
#
#***********************************************************************

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    email_verified = models.BooleanField(
        default = False,
        db_index = True,
    )

    subscribe_email = models.BooleanField(
        default = False,
        db_index = True,
    )

    subscribe_sms = models.BooleanField(
        default = False,
        db_index = True,
    )

    subscribe_whatsapp = models.BooleanField(
        default = False,
        db_index = True,
    )

    online_now = models.BooleanField(
        db_index = True,
        default = False,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


@receiver(post_delete, sender=CustomUser)
def delete_file(sender, instance, *args, **kwargs):

    path = os.path.join(settings.MEDIA_ROOT, str(instance.id))
    try:
        os.rmdir(path)
    except:
        pass




#***********************************************************************
# PACKAGES
#***********************************************************************

class Package(models.Model):

    TENURE_TYPE = (
        (1, "Years"),
        (2, "Months"),
        (3, "Weeks"),
    )

    IS_TRUE = ((True, 'YES'), (False, 'NO'))

    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    package_name = models.CharField(
        max_length = 255,
        blank = False,
        null = False,
        unique = True,
    )

    value = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )

    tenure = models.IntegerField(
        db_index = True,
        null = False,
        blank = False,
    )

    tenure_types = models.IntegerField(
        default = 1,
        choices = TENURE_TYPE,
        db_index = True,
    )

    description = models.TextField(
        null = True,
        blank = True,
    )

    is_active = models.BooleanField(
        default = True,
        choices = IS_TRUE,
        db_index = True,
    )

    created_on = models.DateTimeField(
        auto_now_add = True,
        db_index = True,
        null = True,
        blank = True,
    )

    class Meta:
        verbose_name_plural = "Packages"


#***********************************************************************
# PROFILE
#***********************************************************************

class ConfirmEmail(models.Model):
    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    key = models.CharField(
        max_length = 50,
        db_index = True,
        null = True,
        blank = True
    )

    class Meta:
        verbose_name_plural = "Confirm Emails"

#***********************************************************************
# PROFILE
#***********************************************************************

class Profile(models.Model):
    user = models.ForeignKey(
        CustomUser,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.CASCADE,
    )

    uid = models.CharField(
        max_length = 20,
        blank = True,
        null = True,
        db_index = True,
    )

    package = models.ForeignKey(
        Package,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.SET_NULL,
    )

    fullname = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    MALE = 'M'
    FEMALE = 'F'

    gender_choices = ((MALE, 'Male'), (FEMALE, 'Female'))

    gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )

    looking_for_gender = models.CharField(
        max_length = 1,
        db_index = True,
        null = True,
        blank = False,
        choices = gender_choices,
    )


    father_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = True,
    )

    father_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    mother_job = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,
        blank = False,
    )

    mother_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = True,

app/templates/app/users/index.html
{% load static %}
<div class="row">
	<div class="col-md-4">
		<div class="card-header card-header-blue card-header-border">
			<strong>Activity Monitor</strong>
		</div>
		<div class="card-body card-body-border">
			<div class="row">
				<div class="col">
					<div class="row">
						<div class="col-4">
							<canvas id="myChart" width="100" height="96" style="margin:5px 10px;"></canvas>
						</div>
						<div class="col-8">
							<label style="padding-top:10px;">Monthly Average Activity Status.</label>
							<p>
								Login regularly and respond to interests for better results.
							</p>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
	<div class="col-md-8">
		<div class="card-header card-header-blue card-header-border">
			<strong>Profile</strong>
		</div>
		<div class="card-body-blue card-body-border">
			<div class="row">
				<div class="col">
					<div class="row">
						<div class="col-md-6 col-sm-12 col-xs-12">
							<div class="row">
								<div class="col-md-3 col-sm-12 text-center">
									<img src="{% static 'images/user.png' %}" class="img img-responsive pull-left" width="100px"/>
								</div>
								<div class="col-md-8 col-sm-12">
									<ul class="ul">
										<li> 
											<a href="{% url 'user_profile' %}">
												<span class="mdi mdi-account-circle"></span> &nbsp; Update Profile
											</a>
										</li>
										<li>
											<a href="#" data-toggle="modal" data-target="#profile_picture_modal">
												<span class="mdi mdi-camera"></span> &nbsp; Update Profile Picture
											</a>
										</li>
										<li> 
											<a href="#">
												<span class="mdi mdi-filter"></span> &nbsp; Edit Partner Preferences
											</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-6 col-sm-12 col-xs-12" style="padding:0px 25px;">
							<label style="padding-top:10px;">Profile Completion</label>
							<div class="progress" style="border-radius:12px; height:22px;">
								<div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 79%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
							</div>
							<label style="padding-top:10px;">
								<a href="#">
									<span class="mdi mdi-bell"></span> &nbsp;Edit Notification Settings
								</a>
							</label>
						</div>
					</div>
				</div>
			</div>	
		</div>
    </div>
</div>


<div class="row" style="margin-top:10px;">	

	<div class="col-md-9">

		<div class="card-header card-header-blue card-header-border">
			<strong>Activity Monitor</strong>
		</div>
		<div class="card-body card-body-border" style="padding:10px;">
			<div class="row">
				<div class="col-md-6 col-sm-12 col-xs-12">
					<div class="card-header">
						Interests
					</div>
					<div class="card-body" style="height:100px; padding:10px; font-size:11px; line-height:20px;">
						<table class="table-responsive">
							<tr class="tr-border-bottom">
								<td>Total Accepted</td>
								<td>:</td>
							</tr>
							<tr>							
								<td>Interest Recieved</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Interest Sent</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Waiting for Response</td>	
								<td>:</td>							
							</tr>
						</table>
					</div>
				</div>
				<div class="col-md-6 col-sm-12 col-xs-12">
					<div class="card-header">
						Requests
					</div>
					<div class="card-body" style="height:100px; padding:10px; font-size:11px; line-height:20px;">
						<table class="table-responsive">
							<tr class="tr-border-bottom">
								<td>Photo Requested</td>
								<td>:</td>
							</tr>
							<tr>							
								<td>Photo Request Recieved</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Photo Access Sent</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Photo Access Denied</td>	
								<td>:</td>							
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-sm-12 col-xs-12">
					<div class="card-header">
						Message Center
					</div>
					<div class="card-body" style="height:100px; padding:10px; font-size:11px; line-height:20px;">
						<table class="table-responsive">
							<tr class="tr-border-bottom">
								<td>Unread Messages</td>
								<td>:</td>
							</tr>
							<tr>								
								<td>Messages Sent</td>
								<td>:</td>
							</tr>
							<tr>							
								<td>Messages Recieved</td>
								<td>:</td>
							</tr>							
							<tr>
								<td>Tickets Raised</td>	
								<td>:</td>							
							</tr>
						</table>
					</div>
				</div>
				<div class="col-md-6 col-sm-12 col-xs-12">
					<div class="card-header">
						Profiles Summary
					</div>
					<div class="card-body" style="height:100px; padding:10px; font-size:11px; line-height:20px;">
						<table class="table-responsive">
							<tr class="tr-border-bottom">
								<td>Profiles Viewed</td>
								<td>:</td>
							</tr>
							<tr>							
								<td>Profiles Shortlisted</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Profiles Liked</td>
								<td>:</td>
							</tr>
							<tr>
								<td>Profiles Reported</td>	
								<td>:</td>							
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
		
		<!-- --> 
		{% include 'app/html_components/latest_matches.html' %}	
		
	</div>
	
	<div class="col-md-3">
		{% include 'app/html_components/recent_profiles.html' %}		
		{% include 'app/html_components/side_search_filters.html' %}		
		{% include 'app/modal_forms/connect_modal.html' %}
	</div>
	
</div>



{% include 'app/modal_forms/profile_picture_modal.html' %}

app/templates/app/users/messagecenter.html
<div class="row">


</div>

app/templates/app/users/profile.html
{% load static %}
<div class="row">
	<div class="col-md-12">
		<div class="row">
			<div class="col-8">
				<div class="card-body">
					<table class="table" style="border:none;">
						<tr>
							<td colspan="2" class="bg-success" style="color:#FFFFFF;">
								<span style="font-weight:bold; display:inline-block; line-height:35px;">Package Name</span>
								<button class="btn btn-sm" style="float:right; margin-right: -10px; margin-top: -1px; padding: 8px; background-color:#af27f5; color: #FFF;" data-toggle="modal" data-target="#packagesModal">
									<i class="mdi mdi-square-inc-cash"></i> Upgrade
								</button>
								<span style="font-size:11px; display:inline-block; float:right; text-align:right; margin-right:10px;">
									Remaining Duration
									<br/>1Year
								</span>
							</td>
						</tr>
					</table>
				</div>

				<div class="card-body">
					<table class="table" style="border:none;">
						<tr>
							<td colspan="4" class="bg-info" style="color:#FFFFFF;">
								Summary

								<button class="btn btn-sm btn-warning" style="float:right; margin-right: -10px; margin-top:-3px" data-toggle="modal" data-target="#editProfile_summary_Modal">
									<i class="mdi mdi-pencil"></i> Edit
								</button>
							</td>
						</tr>
						<tr>
							<td>
								<strong>{{ profile.descriptions }}</strong>
							</td>
						</tr>
					</table>
				</div>

			{% comment %} family details {% endcomment %}

			<div class="card-body">
					<table class="table" style="border:none;">
						<tr>
							<td colspan="4" class="bg-info" style="color:#FFFFFF;">
								Family Details

								<button class="btn btn-sm btn-warning" style="float:right; margin-right: -10px; margin-top:-3px" data-toggle="modal" data-target="#edit_family_form_modal">
									<i class="mdi mdi-pencil"></i> Edit
								</button>
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Total Sibling Male </strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.sibling_male|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Total Sibling Female </strong>
							</td>
							<td><strong>:</strong> {{ profile.sibling_female|default_if_none:'-' }}</td>
						</tr>

						<tr>
							<td style="text-align:right;">
								<strong>Total Sibling Elder </strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.sibling_elder|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Total Sibling Younger </strong>
							</td>
							<td><strong>:</strong> {{ profile.sibling_younger|default_if_none:'-' }}</td>
						</tr>

						<tr>
							<td style="text-align:right;">
								<strong>Total Sibling Married </strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.sibling_married|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Total Siblings </strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.siblings|default_if_none:'-' }}
							</td>
						</tr>
						<tr>
						<td style="text-align:right;">
								<strong>Father Occupation</strong>
							</td>
							<td><strong>:</strong> {{ profile.father_job|default_if_none:'-' }}</td>
						
							
							<td style="text-align:right;">
								<strong>Mother Occupation</strong>
							</td>
							<td><strong>:</strong> {{ profile.mother_job|default_if_none:'-' }}</td>
						</tr>
					</table>
				</div>

			{% comment %}  {% endcomment %}
				<div class="card-body">
					<table class="table" style="border:none;">
						<tr>
							<td colspan="4" class="bg-info" style="color:#FFFFFF;">
								My Personal Information

								<button class="btn btn-sm btn-warning" style="float:right; margin-right: -10px; margin-top:-3px" data-toggle="modal" data-target="#editProfileModal">
									<i class="mdi mdi-pencil"></i> Edit
								</button>
							</td>
						</tr>
						<tr>
							<td width="150px" style="text-align:right;">
								<strong>Fullname</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.fullname }}
							</td>
							<td width="150px" style="text-align:right;">
								<strong>Gender</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.get_gender_display }}
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Looking For</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.get_looking_for_gender_display }}
							</td>
							<td style="text-align:right;">
								<strong>Father's Name</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.father_name|default_if_none:'-' }}
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Mother's Name</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.mother_name|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Date Of Birth</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.dob|default_if_none:'-' }}
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Religion</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.religion|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Caste/Domination</strong>
							</td>
							<td><strong>:</strong> {{ profile.caste_creed|default_if_none:'-' }}</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Phone/Mobile</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.phone_number|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Alternative Phone</strong>
							</td>
							<td><strong>:</strong> {{ profile.phone_number_alternative|default_if_none:'-' }}</td>
						</tr>
						
						<tr>
							<td style="text-align:right;">
								<strong>Address</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.address|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Country</strong>
							</td>
							<td colspan="3">
								<strong>:</strong> {{ profile.country |default_if_none:'-' }}
								
							</td>
						</tr>

						
						<tr>
							<td style="text-align:right;">
								<strong>State</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.state|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>City</strong>
							</td>
							<td colspan="3">
								<strong>:</strong> {{ profile.city |default_if_none:'-' }}
								
							</td>
						</tr>
					</table>
				</div>

				<div class="card-body">
					<table class="table" style="border:none;">
						<tr>
							<td colspan="6" class="bg-info" style="color:#FFFFFF;">
								Other Details

								<button class="btn btn-sm btn-warning" style="float:right; margin-right: -10px; margin-top:-3px" data-toggle="modal" data-target="#edit_other_form_modal">
									<i class="mdi mdi-pencil"></i> Edit
								</button>
							</td>
						</tr>
						<tr>
							<td width="150px" style="text-align:right;">
								<strong>Height</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.height|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Weight</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.weight|default_if_none:'-' }}
							</td>
							<td style="text-align:right;">
								<strong>Complexion</strong>
							</td>
							<td>
								<strong>:</strong> {{ profile.complexion|default_if_none:'-' }}
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Educational Qual.</strong>
							</td>
							<td colspan="5">
								<strong>:</strong> {{ profile.qualification|default_if_none:'-' }}
							</td>
						</tr>
						<tr>
							<td style="text-align:right;">
								<strong>Job Details</strong>
							</td>
							<td colspan="5">
								<strong>:</strong> {{ profile.job_details|default_if_none:'-' }}
							</td>
						</tr>
					</table>
				</div>
			</div>



			{% comment %} Sibling {% endcomment %}

			

			<div class="col-4">
				<div class="card-header card-header-border">
					<strong>My Pics</strong>
					<button class="btn btn-sm btn-primary" style="float:right; margin-right: -10px; margin-top:-3px" data-toggle="modal" data-target="#profile_picture_modal"><i class="mdi mdi-plus"></i> Add</button>
				</div>
				<div class="card-body card-body-border" style="min-height:150px;">
					<div class="row" style="padding:10px">
						{% for pics in gallery %}
							<div class="col-4" style="padding:10px">
								<img src="{% get_media_prefix %}{{pics.picture}}" class="img" width="100%" height="auto">
							</div>
						{% endfor %}
					</div>
				</div>

				<!-- Filters -->

				{% include 'app/html_components/side_search_filters.html' %}

			</div>
		</div>
	</div>
</div>
{% include 'app/modal_forms/profile_picture_modal.html' %}
{% include 'app/modal_forms/edit_profile_modal.html' %}
{% include 'app/html_components/packages_list.html' %}

app/templates/app/users/profile1.html
{% load static %}

<div class="row">
	<div class="col-md-12">
		<div class="row">
        </div>
    </div>
</div>